# Generated by Django 4.0.6 on 2024-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proddesc',
            field=models.TextField(blank=True),
        ),
    ]
